-- Humor Project, Assignment #4: captions + caption votes.
-- Safe to re-run: tables are only created if missing, seed only runs on an empty table,
-- and policies are dropped/recreated.
-- Note: this project has an `ensure_rls` event trigger that auto-enables RLS on new
-- public tables, so RLS stays ON and the minimum policies below grant access.

create table if not exists public.captions (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.caption_votes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  caption_id bigint not null references public.captions (id) on delete cascade,
  vote smallint not null check (vote in (1, -1)), -- 1 = upvote, -1 = downvote
  created_at timestamptz not null default now()
);

create index if not exists caption_votes_caption_id_idx on public.caption_votes (caption_id);
create index if not exists caption_votes_user_id_idx on public.caption_votes (user_id);

-- Seed a few captions for testing (only when the table is empty).
insert into public.captions (text)
select t.text
from (
  values
    ('When the group project becomes an individual project.'),
    ('Me pretending I understood the assignment.'),
    ('When the bug disappears before the demo.'),
    ('It works on my machine.'),
    ('Deploying on a Friday afternoon.')
) as t (text)
where not exists (select 1 from public.captions);

-- ---------------------------------------------------------------------------
-- RLS policies (RLS itself is already enabled by the ensure_rls trigger).
-- captions:       anyone (signed in or not) can read.
-- caption_votes:  signed-in users can only INSERT votes as themselves.
--                 No SELECT/UPDATE/DELETE: the app only ever inserts new rows.
-- ---------------------------------------------------------------------------
alter table public.captions enable row level security;
alter table public.caption_votes enable row level security;

drop policy if exists "Anyone can read captions" on public.captions;
create policy "Anyone can read captions"
  on public.captions for select
  to anon, authenticated
  using (true);

drop policy if exists "Users can insert their own votes" on public.caption_votes;
create policy "Users can insert their own votes"
  on public.caption_votes for insert
  to authenticated
  with check ((select auth.uid()) = user_id);
